name: Publish Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "Path to the Dockerfile"
        required: true
        type: string
      build-context:
        description: "Path to the build context, optional"
        required: false
        type: string
        default: "."
      tags:
        description: "Line list of tags for the image"
        required: true
        type: string
      image_name:
        description: "Image name, e.g. owner/repo"
        required: false
        type: string
        default: ${{ github.repository }}
      changelog:
        description: "Changelog to put into a changelog.md file, optional"
        required: false
        type: string
      changelog-path:
        description: "Path to download the changelog artifact, optional"
        required: false
        type: string
        default: "changelog.md"
    outputs:
      image-digest:
        description: "image digest"
        value: ${{ jobs.ImagePublisher.outputs.image-digest }}
      image-id:
        description: "Image ID"
        value: ${{ jobs.ImagePublisher.outputs.image-id }}
      image-metadata:
        description: "Build result metadata"
        value: ${{ jobs.ImagePublisher.outputs.image-metadata }}

jobs:

  ImagePublisher:
    outputs:
      image-digest: ${{ steps.build-and-push.outputs.digest }}
      image-id: ${{ steps.build-and-push.outputs.imageid }}
      image-metadata: ${{ steps.build-and-push.outputs.metadata }}
    runs-on: lite
    container:
      image: ghcr.io/catthehacker/ubuntu:runner-24.04-20260222
    steps:
      - name: Git Checkout
        uses: actions/checkout@v7.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.1.0
        with:
          driver: 'remote'
          endpoint: tcp://buildkit:1234
          name: 'remote'

      - name: Create changelog
        run: |
          echo "${{ inputs.changelog }}" >> "${{ inputs.changelog-path }}"

      - name: Create image name list
        run: |
          IMAGE_NAMES=$(echo "${{ inputs.tags }}" | sed 's|^|ghcr.io/:|')
          echo "IMAGE_NAMES<<EOF" >> $GITHUB_ENV
          echo "$IMAGE_NAMES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Image list
        run: |
          echo "IMAGE_NAMES=${{ env.IMAGE_NAMES }}"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v7.2.0
        with:
          context: ${{ inputs.build-context }}
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: "${{ env.IMAGE_NAMES }}"
