name: "Semantic commit linter"

on:
  workflow_call:

jobs:
  validate-commits:
    runs-on: lite

    container:
      image: ghcr.io/catthehacker/ubuntu:runner-24.04-20260222

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: '0'
      - name: Commitsar check
        uses: docker://aevea/commitsar:1.0.3
