name: Semantic Releaser

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      published:
        description: "Whether a new release was created"
        value: ${{ jobs.SemanticRelease.outputs.published }}
      version:
        description: "The released version tag"
        value: ${{ jobs.SemanticRelease.outputs.new_release_version }}
      notes:
        description: "Release notes"
        value: ${{ jobs.SemanticRelease.outputs.new_release_notes }}

jobs:

  SemanticRelease:
    runs-on: lite

    container:
      image: ghcr.io/catthehacker/ubuntu:runner-24.04-20260222

    outputs:
      new_release_version: ${{ steps.release.outputs.new_release_version }}
      new_release_notes: ${{ steps.release.outputs.new_release_notes }}
      published: ${{ steps.release.outputs.new_release_published }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6.0.2

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
